version: "3.9"
services:
  nodejs:
    container_name: node
    image: node:19-alpine3.16
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 3030:3030
    networks:
      - backend-network
    working_dir: /www
    volumes:
      - ./src:/www
  mongo:
    container_name: mongo
    image: mongo:6.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}
    networks:
      - backend-network
    volumes:
      - ./database/mongo/db:/data/db
  mongo-express:
    container_name: mongo_express
    image: mongo-express:1.0.0-alpha
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 8081:8081 
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_DB_ROOT_USERNAME}:${MONGO_DB_ROOT_PASSWORD}@mongo:27017/?authSource=admin
    networks:
      - backend-network
networks:
  backend-network: