version: "3.9"
services:
  nodejs:
    container_name: api
    image: 19-alpine3.16
    restart: always
    ports:
      - 3030:3030
    networks:
      - backend-network
    working_dir: /www
    volumes:
      - ./dist:/www
  mongodb:
    container_name: main_db
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_ROOT_USERNAME}"
      - MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_ROOT_PASSWORD}"
    networks:
      - backend-network
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_DB_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_DB_ROOT_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_DB_ROOT_USERNAME}:${MONGO_DB_ROOT_PASSWORD}@localhost:27017/"
    networks:
      - backend-network
networks:
  backend-network: